### ISSUE TITLE
GUI for passing parameters before a rendering from IDE ? 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-r#132]
See 
* https://github.com/rstudio/rstudio/issues/13937

Would be a bit like `params = "ask"` in **rmarkdown**

**Comment by Mosk915** [comment]
For me, this is probably the biggest feature of Rmarkdown that is missing from Quarto.  Would love to see this get added.

**Comment by cderv** [comment]
@Mosk915 Can you share details on how you are using it in R Markdown context ? What exactly are you missing ? What is your workflow and use case ? 

This will help design something that works well. Thanks

**Comment by Mosk915** [comment]
@cderv At my company, we frequently create reports which require extracting data from a database.  In order to ensure the person running the report is allowed to access the data, we make the database credentials parameters in the R Markdown.  The report may have other parameters as well.  Many of the users running the report do not write code at all, so their workflow is to just open up the `.Rmd` file in RStudio, click the dropdown next to the `Knit` button, and then select `Knit with Parameters`.

Here's an example of what the `params` part of the yaml might look like.

```
params:
  username:
    label: "Username"
    input: text
    value: ""
  password:
    label: "Password"
    input: password
    value: ""
  states:
    label: "States"
    input: select
    choices: [Alabama, Arizona, Arkansas]
    value: Alabama
```

And here is what the user would enter when knitting the report.

<img width="621" height="457" alt="Image" src="https://github.com/user-attachments/assets/29aa08f8-1df4-4b7f-a206-8df95059f532" />

Over the years I've probably used most of the different input types described here:
https://bookdown.org/yihui/rmarkdown/params-knit.html

For parameterized Quarto reports, I've tried to replicate this behavior by creating a small shiny app, which works, but ultimately isn't as easy to use as the built-in capability of R Markdown.

I realize this issue is only for implementing the GUI in the quarto package, not within RStudio.  But my hope is that if it were implemented here, it could then be added to RStudio and work the same way it does for R Markdown.
