### ISSUE TITLE
Custom Quarto Extension/Template for Vignette Building

### ISSUE THREAD

**Issue by jan-abel-inwt** [quarto-dev/quarto-r#166]
Hi there, I just tested the feature of building vignettes with Quarto, and it works seamlessly!

I read [this article](https://quarto-dev.r-universe.dev/articles/quarto/hello.html) which states that the following configuration can't be overridden:

```
format: 
  html:
    theme: none
    minimal: true
    embed-resources: true
    css: custom.css
```

I'm wondering how to build a vignette with my own custom Quarto extension/template. Is this possible?
