### ISSUE TITLE
Problem knitting fonts with ligatures/alternates to PDF 

### ISSUE THREAD

**Issue by mbac** [quarto-dev/quarto-r#17]
Hi,

I'm using [Fira Code](https://github.com/tonsky/FiraCode) as a monospace font, but the same is happening when trying with [JetBrains Mono](https://www.jetbrains.com/lp/mono/).

When I render to HTML, all ligatures and alternates are present and looking fine, e.g.:

<img width="457" alt="Screen Shot 2022-07-01 at 16 16 05" src="https://user-images.githubusercontent.com/308068/176911805-8e2013c8-cf78-4aec-8876-02611bc3f085.png">

However, knitting to PDF results in just one of them showing up, and several "standard" glyphs (letters) missing:

<img width="416" alt="Screen Shot 2022-07-01 at 16 15 43" src="https://user-images.githubusercontent.com/308068/176912043-37a8246c-daa6-4d59-b961-cd91f4e3b500.png">

(it's missing opening brackets, and the whole `echo: false` sentence in the last paragraph)

This is the code I'm using (note that the PDF output doesn't change whether I specify `monofontoptions:` or not):

````
---
title: "Test"
author: "MB"
editor: visual

format:
  html:
    theme: journal
    fontsize: 12pt
    monofont: Fira Code
    mainfont: SF Pro Display
  pdf:
    fontsize: 10pt
    monofont: Fira Code
    monofontoptions: 
      - Ligatures = TeX
    mainfont: SF Pro Text
    sansfont: SF Pro Text
    highlight-style: github
    papersize: a4
    cite-method: biblatex
    documentclass: article
---

```{r}
1 + 1

a <- 4

# 3 != 5
```

You can add options to executable code like this

```{r}
#| echo: false
2 * 2


```
````

Thanks,
—M
