### ISSUE TITLE
crossref table error

### ISSUE THREAD

**Issue by hao203** [quarto-dev/quarto-r#61]
Hello,
There is a bug.
```r
#| label: tbl-birth
#| tbl-cap: "Birth table"
load("dataset/births.rda") %>% 
births
```
_quarto.yml  settings

``` yaml
format:
  html:
    theme: cosmo
    df-print: paged
```
@tbl-birth

WARNING: 03-tidy_data.html: Unable to resolve crossref @tbl-birth
Watching files for changes

The crossref is available when I change the code block, but it's not paged

```r
#| label: tbl-birth
#| tbl-cap: "Birth table"
births <- import("dataset/births.rda")  
knitr::kable(births)
```

I want both of crossref and paged available
