### ISSUE TITLE
post-render in header of .qmd-file

### ISSUE THREAD

**Issue by avraam-inside** [quarto-dev/quarto-r#62]
Hi!

Recently, the `post-render` functionality has been introduced. This is a great thing, thank you!

But I have a need to refine this functionality: I have a multi-module project with a lot of subdirectories where quarto is just one of many modules. I would like to be able to embed the post-render into the `.qmd`-file in the header. For example:

```yml
---
title: 'test'
format: 
    html:
        number-sections: TRUE
        theme: cosmo
        toc: TRUE
post-render: tmp.R
---
```

And accordingly,the file will be launched `tmp.R` which is located in the folder where the `.qmd`-file itself lies  (the folder in knit/render mode is successfully located via `getwd()`).

It is important for me to navigate in the current folder where the current `.qmd`-file is located, and not in the entire project

So far, I have to use crutches at the level of the entire project, which is not very good.

I would be grateful if you think about such improvements, thank you!
