### ISSUE TITLE
Add cross-referencing for citations

### ISSUE THREAD

**Issue by Nischal-Karki-ATW** [quarto-dev/quarto-r#70]
The citations don't have hyperlinks when output to pdf or word. Other cross-references work as intended. How do I add hyperlinks to the citations?

**Comment by dragonstyle** [comment]
You can use the option `link-citations: true` in your front matter to enable this. For example:

```yaml
title: Document
author: Norah Jones
format:
  pdf:
    link-citations: true
```

This element is missing from our PDF reference - I am transferring this issue to the main Quarto repo track adding it.
